### PR TITLE
update force mode

### PR DESCRIPTION
**Pull request by LukasLow**
view in https://github.com/pourmand1376/obsidian-custom-font/issues/5

### CODE REVIEW

**Comment by LukasLow** [comment]
ok now with theme the text would not update :(

**Comment by pourmand1376** [comment]
Could you please explain Why this PR is necessary and What it does? 

Honestly, It is unclear from the code what you wanted to do. 

Do you want to disable Force Mode when custom CSS is applied?

**Comment by LukasLow** [comment]
Hi Amir,

Let me clarify the purpose and functionality of the changes made in this pull request (PR).

The primary goal of these changes is to refine the way force_mode applies font settings, ensuring it's both effective and less intrusive. This is achieved by providing more nuanced control over font styling, particularly under force_mode conditions.

Refinement of force_mode Application:

**Original Approach**: Previously, force_mode applied the font-family property globally to all elements using the * selector, which was quite aggressive and led to overriding all other and custom CSS font-family rules.
**New Approach**: The introduction of the addImportantToCSS() function ensures that force_mode is applied more selectively. This function adds !important to each individual CSS rule, as opposed to applying it globally. This method ensures the precedence of force_mode settings without broadly overriding other styles, thus maintaining better control over the CSS styling.
Enhancements to get_default_css Function:

**Original Functionality**: The function was initially setting various CSS custom properties related to fonts.
**Enhancements Made**: The modified function now includes a direct application of the font-family property to div span elements, in addition to setting custom properties. This targeted approach reduces the likelihood of global overrides. Additionally, the function now adds more font-related custom properties, offering greater flexibility and customization options.

**Addressing Your Query**:
The changes are not about disabling force_mode when custom CSS is applied. Instead, they aim to make force_mode more compatible with custom styling by ensuring it doesn't completely override user-defined styles. The idea is to enhance user experience by offering a more balanced approach between force_mode enforcement and custom CSS application.
In essence, these changes improve the flexibility and usability of CSS styling functionality in our project, particularly in scenarios where force_mode is active. They allow for more precise control over font styling, ensuring that force_mode enhancements are applied effectively without disrupting the overall styling intentions.

I hope this explanation clarifies the intent and functionality of the changes proposed in this PR.

**Comment by pourmand1376** [comment]
Sorry. AI generated answers don't help here. Please have some respect and provide the answer yourself.

**Comment by LukasLow** [comment]
thank you, this works : ) 
but for ease of use (changing font) i would like to keep the changes in the code, I hope you're cool with me changing my repo to a version that works with a git clone. I will not upload it to obsidians plugin list because it basically the same.

Btw: .otf files work with your plugin too and above i needed to change it to `font-family: YourFontFamilyName !important;
`

**Comment by pourmand1376** [comment]
Who am I to have problem with that? I have made the License Apache just to make sure that anyone can do any changes he/she wants and be happy with it.

**Comment by LukasLow** [comment]
Thx

**Pull request closed without merging**
